name: Halliburton x InvisiRisk

on:
  schedule:
    - cron: '45 0 * * 1'  # every Monday at 12:45 AM UTC (6:30 AM NPT)
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    name: Sync fork and Run build

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{secrets.IR_API_KEY}}
      # ============= InvisiRisk Setup End =============
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Or 'zulu', 'adopt', etc.
          java-version: '17'       # Use the Java version you need

     # - name: Run tests for stable modules
      #  run: |
       #   mvn verify -DfailIfNoTests=false -DtestFailureIgnore=false

      - name: Try building problematic modules (non-blocking)
        run: |
          mvn install -DskipTests -pl ua/org.eclipse.ua.tests,ua/org.eclipse.ua.tests.doc || echo "Skipping missing test modules"

      - name: Try running tests in problematic modules (non-blocking)
        run: |
          mvn verify -DfailIfNoTests=false -DtestFailureIgnore=true -pl ua/org.eclipse.ua.tests,ua/org.eclipse.ua.tests.doc || echo "Tests failed or module not found, ignoring"
      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
