name: Halliburton x InvisiRisk

on:
  schedule:
    - cron: '45 2 * * *'
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    name: Sync fork and Run build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
         git config user.name "ir-pranesh-shrestha"
          git config user.email "pranesh.shrestha@invisirisk.com"
          
      - name: Add upstream and sync fork
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          git remote add upstream https://github.com/Halliburton-Landmark/eclipse.platform.ui.git
          git fetch upstream
          git checkout dsg-4_30
          git merge upstream/dsg-4_30 --no-edit
          git push https://x-access-token:${GITHUB_TOKEN}github.com/ir-pranesh-shrestha/eclipse.platform.ui-Halliburton dsg-4_30
          
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_PROD }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Or 'zulu', 'adopt', etc.
          java-version: '17'       # Use the Java version you need

      - name: Build all modules with tests skipped
        run: |
          mvn clean install -DskipTests

     # - name: Run tests for stable modules
      #  run: |
       #   mvn verify -DfailIfNoTests=false -DtestFailureIgnore=false

      - name: Try building problematic modules (non-blocking)
        run: |
          mvn install -DskipTests -pl ua/org.eclipse.ua.tests,ua/org.eclipse.ua.tests.doc || echo "Skipping missing test modules"

      - name: Try running tests in problematic modules (non-blocking)
        run: |
          mvn verify -DfailIfNoTests=false -DtestFailureIgnore=true -pl ua/org.eclipse.ua.tests,ua/org.eclipse.ua.tests.doc || echo "Tests failed or module not found, ignoring"

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
